disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Deathstalker"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "/img/scorpin.png"
description = "It's truly a skill of great men to make sense out of nonsense."

[[params.author.links]]
email = "sweetimpurities11f@gmail.com"
github = "https://github.com/c1ph3rbnuk"
twitter = "https://x.com/c1ph3rbnuk"

["params.author"]
name = "Peter Kinyumu"
image = "/img/profile.jpg"
headline = "Doing the things that scare me the most"
bio = "I like to make sense out of nonsense"
